name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag mezorian/mail-health-exporter:${GITHUB_SHA}

    - name: Push Docker image to Docker Hub
      run: docker push mezorian/mail-health-exporter:${GITHUB_SHA}
